### PR TITLE
Kh2 web 1/setup ts project

### PR DESCRIPTION
**Pull request by dima-diachkov**
Create react app with TS has been set up. Have been added node packages (yarn, react-router, react-redux, axios, material UI).

### CODE REVIEW

**Review by artemhoriuk1994 — COMMENTED** [review]
`import React from 'react';

function App() {
  return (
    <div className="App">
      What to watch
    </div>
  );
}

export default App;`

I think you need to add a `<h1>` tag here
as this is the main title of our page

**Review by ananaple — COMMENTED** [review]
nice job

**Review by ananaple — COMMENTED** [review]
like, subscribe

**Review by maria-khudolii — COMMENTED** [review]
seems ok to me

**Comment by sergeyman** [comment]
Good job

**Review by sergeyman — COMMENTED** [review]
My review comment

**Pull request merged**
